version: "3"

services:
  web:
    image: yardstick_web
    build:
      context: ../..
      dockerfile: ./docker/dev/Dockerfile # we changed context above to the root of the project
    environment:
      NODE_ENV: 'development'
    volumes:
      - ../..:/app        # share your code with the containers
    ports:
      - "3000:3000"
      - "9229:9229" # node debugger
    command: yarn start:dev
    depends_on:
      - docker_postgres

  docker_postgres:
    image: postgres:10.3
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: yardstick_dev # TODO(kacper): use  env vars
